In [34]:
import numpy as np

In [53]:
np_countries=np.array(['Great Britain','China','Russia','United States','Korea','Japan','Germany'])
np_country_Code=np.array(['GBR','CHN','RUS','US','KOR','JPN','GER'])
np_year=np.array([2012,2012,2012,2012,2012,2012,2012])
np_gold=np.array([29,38,24,46,13,7,11])
np_silver=np.array([17,28,25,28,8,14,11])
np_bronze=np.array([19,22,32,29,7,17,14])
np_medal_tally=np.array([np_gold,np_silver,np_bronze])

In [54]:
country_max_gold=np_countries[np_gold.argmax()]
print(country_max_gold)

United States


In [55]:
np_countries[np_gold>20]

array(['Great Britain', 'China', 'Russia', 'United States'], dtype='<U13')

In [56]:
print(np_medal_tally)

[[29 38 24 46 13  7 11]
 [17 28 25 28  8 14 11]
 [19 22 32 29  7 17 14]]


In [57]:
for i in range(len(np_countries)):
    print('{} with {} Gold medals'.format(np_countries[i],np_gold[i]))

Great Britain with 29 Gold medals
China with 38 Gold medals
Russia with 24 Gold medals
United States with 46 Gold medals
Korea with 13 Gold medals
Japan with 7 Gold medals
Germany with 11 Gold medals


In [58]:
for i in range(len(np_countries)):
    total_medals=np_gold[i]+np_silver[i]+np_bronze[i]
    print("{} with {} total medals".format(np_countries[i],total_medals))

Great Britain with 65 total medals
China with 88 total medals
Russia with 81 total medals
United States with 103 total medals
Korea with 28 total medals
Japan with 38 total medals
Germany with 36 total medals
